<?php $slides = $block->getBannerCollection();?>
<?php if($slides):?>
    <div id="owl-demo" class="owl-carousel owl-theme">
        <?php foreach($slides as $slide ):?>
           <div class="item">
              <?php if($slide->getImage()): ?>
                <img width="70" height="70" src="<?php echo $block->getBaseUrl().'pub/media/'.$slide->getImage(); ?>">
            <?php else: ?>
                <p>No Image</p>
            <?php endif; ?>
          </div>
        <?php endforeach;?>
    </div>
<?php endif;?>     


<style type="text/css">
 #owl-demo .item img{
      display: block;
      width: 100%;
      height: auto;
  }
</style>
<script type="text/javascript">
  require([
        'jquery',
        'owl.carousel'
      ], function ($) {

     $("#owl-demo").owlCarousel({ 
      navigation : true, // Show next and prev buttons 
      slideSpeed : 300,
      paginationSpeed : 400, 
      items : 1, 
      itemsDesktop : false,
      itemsDesktopSmall : false,
      itemsTablet: false,
      itemsMobile : false 
    });
  });
</script>

